### PR TITLE
Fixed Ctrl+C correct exiting

### PR DESCRIPTION
**Pull request by mixalbl4-127**

### CODE REVIEW

**Comment by huan** [comment]
Hi @mixalbl4-127 ,

Thanks for creating the PR.

Could you please explain the problem and your solution so that we can learn what you are trying to fix?

**Comment by mixalbl4-127** [comment]
Hi @huan 
when you make for example `Connect.desktop` shortcut in folder with sshpass command for easy connect and try to abort it using `ctrl+c` its not working because of `setsid`

**Review by huan — APPROVED** [review]
LGTM

**Comment by huan** [comment]
Hi @mixalbl4-127 , please add an entry in README (I have created it for you). After that, this PR will be ready to be merged.

Thank you very much for your contribution!

**Comment by mixalbl4-127** [comment]
@huan done :)

**Comment by huan** [comment]
Thank you very much, @mixalbl4-127 !

**Pull request merged**
